version: '3.1'
services:
  strava-app:
    image: jmillnerdev/strava-app:${TAGS}
    restart: always
    environment:
      STRAVA_ACCESS_TOKEN: ${STRAVA_ACCESS_TOKEN}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_URL: https://www.strava.com/oauth/mobile/authorize
      STRAVA_OAUTH_URL: https://www.strava.com/oauth/token
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
      - "prometheus-spring"
    labels:
      kompose.service.type: LoadBalancer

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="root"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  prometheus-spring:
    image: jmillnerdev/prometheus-spring
    restart: always
    ports:
      - "9090:9090"
    labels:
      kompose.service.type: LoadBalancer

