version: '3.7'
services:

  strava-app:
    image: jmillnerdev/strava-app
    restart: always
    environment:
      STRAVA_ACCESS_TOKEN: ${STRAVA_ACCESS_TOKEN}
      STRAVA_CLIENT_ID: ${STRAVA_CLIENT_ID}
      STRAVA_CLIENT_SECRET: ${STRAVA_CLIENT_SECRET}
      STRAVA_URL: https://www.strava.com/oauth/mobile/authorize
      STRAVA_OAUTH_URL: https://www.strava.com/oauth/token
      PROFILE: docker
    ports:
      - "8080:8080"
    depends_on:
      - "mongodb"
      - "prometheus"
    labels:
      kompose.service.type: LoadBalancer

  mongodb-exporter:
    image: mongodb_exporter
    hostname: mongodb-exporter
    ports:
      - 9001:9001
    # You can provide custom params to the exporter, according to your mongodb config, like SSL support, ...
    command: -mongodb.uri mongodb://mongodb:27017/strava -mongodb.collect.database -mongodb.collect.connpoolstats -mongodb.collect.collection -mongodb.collect.profile -mongodb.collect.replset=false -mongodb.collect.oplog=false

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_USER="root"
      - MONGODB_PASS="root"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - type: bind
        source: ./prometheus/prometheus-config.yaml
        target: /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    user: "104"
    depends_on:
      - "prometheus"
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always
