management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: ["health", "info", "metrics", "trace", "prometheus"]

spring:
  servlet:
    multipart:
      max-file-size: 5MB


strava:
  url: ${STRAVA_BASEURL}
  accessToken: ${STRAVA_ACCESS_TOKEN}
  clientId: ${STRAVA_CLIENT_ID}
  clientSecret: ${STRAVA_CLIENT_SECRET}
  OAuthUrl: ${STRAVA_OAUTH_URL}
